"""Login-shell-neutral remote argv contract (Wave 1–2).

Remote commands are space-joined already-validated tokens.  This module does
not POSIX-quote, escape, or launch OpenSSH.

A serve session token is generated by the desktop host for one start attempt,
passed as an argv token, and persisted only as a hash in remote owner metadata.

Serve is the one verb that carries the fixed `exec` prefix.  Without it a csh
login shell keeps a forked intermediate process, so the server binds its
PR_SET_PDEATHSIG watch to that shell instead of the sshd session and outlives an
abrupt tunnel loss.  `exec` is a builtin in sh, ksh, bash, zsh, csh and tcsh, so
the prefix stays login-shell neutral and adds no arbitrary shell code.
"""

from __future__ import annotations

import hashlib
import re
import secrets
import uuid
from typing import Iterable, Sequence


REMOTE_PYTHON_REQUIRED = "REMOTE_PYTHON_REQUIRED"
R5_OWNERSHIP_NOT_IMPLEMENTED = "R5_OWNERSHIP_NOT_IMPLEMENTED"
REMOTE_SESSION_TOKEN_INVALID = "REMOTE_SESSION_TOKEN_INVALID"
REMOTE_ENTRY_RELATIVE = "desktop/python-webview-shell/remote_entry.py"
LOOPBACK_HOST = "127.0.0.1"
MAX_PROBE_BYTES = 4096
SESSION_TOKEN_HEX_BYTES = 16

POSIX_PATH_PATTERN = re.compile(r"^/[A-Za-z0-9._/-]+$")
SAFE_TOKEN_PATTERN = re.compile(r"^[A-Za-z0-9._/=:-]+$")
OWNER_PATTERN = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]{0,31}$")
PROVISION_INSTALL_COMMAND = "provision-install"
SERVE_EXEC_PREFIX = "exec"

FORBIDDEN_FRAGMENTS = (
    "&&",
    "||",
    ";",
    "2>&1",
    ">/dev/null",
    "$(",
    "`",
    "bash -lc",
    "python -c",
    "python3 -c",
    "cd --",
    "<<",
)

BARE_INTERPRETERS = frozenset({"python", "python3"})


class RemoteCommandError(RuntimeError):
    def __init__(self, code: str, detail: str = "") -> None:
        self.code = code
        message = code if not detail else f"{code}: {detail}"
        super().__init__(message)


def validated_posix_path(value: object, field: str) -> str:
    if not isinstance(value, str):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", f"{field} must be a string")
    if any(ord(character) < 32 or character == "\x7f" for character in value):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", f"{field} contains a control character")
    if value == "/":
        raise RemoteCommandError(
            "REMOTE_PROTOCOL_INVALID",
            f"{field} must not be the Linux filesystem root",
        )
    if not POSIX_PATH_PATTERN.fullmatch(value):
        raise RemoteCommandError(
            "REMOTE_PROTOCOL_INVALID",
            f"{field} must match ^/[A-Za-z0-9._/-]+$",
        )
    if value.endswith("/"):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", f"{field} must not have a trailing slash")
    segments = value.split("/")[1:]
    if not segments or any(segment in {"", ".", ".."} for segment in segments):
        raise RemoteCommandError(
            "REMOTE_PROTOCOL_INVALID",
            f"{field} must not contain empty, '.' or '..' segments",
        )
    return value


def require_safe_token(token: str) -> str:
    if token in BARE_INTERPRETERS:
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "bare python interpreter is not a token")
    if token == "-c":
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "python -c is not a token")
    if not SAFE_TOKEN_PATTERN.fullmatch(token):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", f"unsafe token {token!r}")
    return token


def require_session_token(value: object) -> str:
    """Require a caller-supplied runtime token. Do not invent a persisted default."""

    if value is None or value == "":
        raise RemoteCommandError(
            R5_OWNERSHIP_NOT_IMPLEMENTED,
            "session_token must be supplied by the desktop start attempt",
        )
    if not isinstance(value, str):
        raise RemoteCommandError(REMOTE_SESSION_TOKEN_INVALID, "session_token must be a string")
    if set(value) <= {"0"}:
        raise RemoteCommandError(
            REMOTE_SESSION_TOKEN_INVALID,
            "all-zero sentinel is not a runtime ownership token",
        )
    return require_safe_token(value)


def generate_session_token() -> str:
    """Return a cryptographically random token that satisfies the argv grammar.

    A hex token ending in `cd` would join with the next serve flag into the
    forbidden fragment `cd --`, so admission is checked at the same boundary the
    joined command uses instead of at the token alone.
    """

    while True:
        token = secrets.token_hex(SESSION_TOKEN_HEX_BYTES)
        if set(token) <= {"0"} or forbidden_fragments(f"{token} --"):
            continue
        return require_session_token(token)


def token_hash(value: object) -> str:
    token = require_session_token(value)
    return hashlib.sha256(token.encode("ascii")).hexdigest()


def path_identity(value: str) -> str:
    canonical = validated_posix_path(value, "path")
    return hashlib.sha256(canonical.encode("ascii")).hexdigest()


def forbidden_fragments(command: str) -> tuple[str, ...]:
    return tuple(fragment for fragment in FORBIDDEN_FRAGMENTS if fragment in command)


def refuse_misplaced_exec(argv: Sequence[str]) -> None:
    """Generic joining is exec-free. The audited serve builder admits `exec`."""

    if any(token == SERVE_EXEC_PREFIX for token in argv):
        raise RemoteCommandError(
            "REMOTE_PROTOCOL_INVALID",
            "exec is admissible only as the leading serve prefix",
        )


def _joined_command(validated: Sequence[str]) -> str:
    if not validated:
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "remote command has no tokens")
    command = " ".join(validated)
    hits = forbidden_fragments(command)
    if hits:
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "forbidden fragments: " + ",".join(hits))
    return command


def _expected_serve_argv(tokens: Sequence[str]) -> list[str]:
    if len(tokens) != 19 or tokens[0] != SERVE_EXEC_PREFIX:
        raise RemoteCommandError(
            "REMOTE_PROTOCOL_INVALID",
            "exec is admissible only as the complete serve argv",
        )
    try:
        remote_port = int(tokens[13])
        local_forward_port = int(tokens[15])
    except (TypeError, ValueError) as error:
        raise RemoteCommandError(
            "REMOTE_PROTOCOL_INVALID",
            "serve argv is not the audited shape",
        ) from error
    return serve_tokens(
        remote_python=tokens[1],
        remote_app_dir=tokens[7],
        remote_data_dir=tokens[9],
        remote_port=remote_port,
        local_forward_port=local_forward_port,
        session_token=tokens[17],
        host=tokens[11],
    )


def join_remote_tokens(tokens: Sequence[str]) -> str:
    validated = [require_safe_token(token) for token in tokens]
    refuse_misplaced_exec(validated)
    return _joined_command(validated)


def join_exact_serve_tokens(tokens: Sequence[str]) -> str:
    """Join only the complete audited serve argv, including the fixed `exec` prefix."""

    validated = [require_safe_token(token) for token in tokens]
    expected = _expected_serve_argv(validated)
    if validated != expected:
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "serve argv is not the audited shape")
    return _joined_command(validated)


def remote_entry_path(app_dir: str) -> str:
    root = validated_posix_path(app_dir, "remote_app_dir")
    return validated_posix_path(f"{root}/{REMOTE_ENTRY_RELATIVE}", "remote_entry")


def require_remote_python(value: object) -> str:
    if value is None or value == "":
        raise RemoteCommandError(REMOTE_PYTHON_REQUIRED)
    return validated_posix_path(value, "remote_python")


def overlapping_posix_roots(left: str, right: str) -> bool:
    return left == right or left.startswith(right + "/") or right.startswith(left + "/")


def require_posix_owner(value: object) -> str:
    if not isinstance(value, str) or not OWNER_PATTERN.fullmatch(value):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "owner is not a POSIX user name")
    return value


def require_workspace_uid(value: object) -> str:
    if not isinstance(value, str):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "workspace uid is invalid")
    if any(ord(character) < 32 or character == "\x7f" for character in value):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "workspace uid is invalid")
    try:
        parsed = uuid.UUID(value)
    except (ValueError, AttributeError):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "workspace uid is invalid") from None
    if value != str(parsed) or parsed.int == 0 or parsed.variant != uuid.RFC_4122:
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "workspace uid is invalid")
    return value


def provision_install_tokens(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    owner: object,
    expected_workspace_uid: object,
) -> list[str]:
    python = require_remote_python(remote_python)
    install = validated_posix_path(remote_app_dir, "remote_app_dir")
    data = validated_posix_path(remote_data_dir, "remote_data_dir")
    user = require_posix_owner(owner)
    uid = require_workspace_uid(expected_workspace_uid)
    if overlapping_posix_roots(install, data):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "install and data roots must be separate")
    return [
        python,
        "-I",
        "-B",
        "-",
        PROVISION_INSTALL_COMMAND,
        "--install-root",
        install,
        "--data-root",
        data,
        "--owner",
        user,
        "--expected-workspace-uid",
        uid,
    ]


def probe_tokens(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    session_token: object = None,
) -> list[str]:
    python = require_remote_python(remote_python)
    app = validated_posix_path(remote_app_dir, "remote_app_dir")
    data = validated_posix_path(remote_data_dir, "remote_data_dir")
    tokens = [
        python,
        "-I",
        "-B",
        remote_entry_path(app),
        "probe",
        "--app-dir",
        app,
        "--data-dir",
        data,
    ]
    if session_token is None or session_token == "":
        return tokens
    return tokens + ["--session-token", require_session_token(session_token)]


def serve_tokens(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    remote_port: int,
    local_forward_port: int,
    session_token: object,
    host: str = LOOPBACK_HOST,
) -> list[str]:
    python = require_remote_python(remote_python)
    app = validated_posix_path(remote_app_dir, "remote_app_dir")
    data = validated_posix_path(remote_data_dir, "remote_data_dir")
    token = require_session_token(session_token)
    return [
        SERVE_EXEC_PREFIX,
        python,
        "-I",
        "-B",
        remote_entry_path(app),
        "serve",
        "--app-dir",
        app,
        "--data-dir",
        data,
        "--host",
        require_safe_token(host),
        "--port",
        require_safe_token(str(remote_port)),
        "--public-port",
        require_safe_token(str(local_forward_port)),
        "--session-token",
        token,
        "--exit-with-parent",
    ]


def stop_owned_tokens(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    session_token: object,
) -> list[str]:
    python = require_remote_python(remote_python)
    app = validated_posix_path(remote_app_dir, "remote_app_dir")
    data = validated_posix_path(remote_data_dir, "remote_data_dir")
    token = require_session_token(session_token)
    return [
        python,
        "-I",
        "-B",
        remote_entry_path(app),
        "stop-owned",
        "--data-dir",
        data,
        "--session-token",
        token,
    ]


def join_probe_command(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    session_token: object = None,
) -> str:
    tokens = probe_tokens(
        remote_python=remote_python,
        remote_app_dir=remote_app_dir,
        remote_data_dir=remote_data_dir,
        session_token=session_token,
    )
    scan_tokens_for_live_ssh(tokens)
    return join_remote_tokens(tokens)


def join_serve_command(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    remote_port: int,
    local_forward_port: int,
    session_token: object,
    host: str = LOOPBACK_HOST,
) -> str:
    tokens = serve_tokens(
        remote_python=remote_python,
        remote_app_dir=remote_app_dir,
        remote_data_dir=remote_data_dir,
        remote_port=remote_port,
        local_forward_port=local_forward_port,
        session_token=session_token,
        host=host,
    )
    scan_tokens_for_live_ssh(tokens)
    return join_exact_serve_tokens(tokens)


def join_stop_owned_command(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    session_token: object,
) -> str:
    tokens = stop_owned_tokens(
        remote_python=remote_python,
        remote_app_dir=remote_app_dir,
        remote_data_dir=remote_data_dir,
        session_token=session_token,
    )
    scan_tokens_for_live_ssh(tokens)
    return join_remote_tokens(tokens)


def join_provision_install_command(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    owner: object,
    expected_workspace_uid: object,
) -> str:
    tokens = provision_install_tokens(
        remote_python=remote_python,
        remote_app_dir=remote_app_dir,
        remote_data_dir=remote_data_dir,
        owner=owner,
        expected_workspace_uid=expected_workspace_uid,
    )
    scan_tokens_for_live_ssh(tokens)
    return join_remote_tokens(tokens)


def scan_tokens_for_live_ssh(argv: Iterable[str]) -> None:
    """Refuse accidentally embedding a live ssh invocation in remote tokens."""

    for token in argv:
        if token == "ssh" or token.endswith("/ssh") or token.endswith("ssh.exe"):
            raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "live ssh is not a remote token")
