"""Login-shell-neutral remote argv contract (Wave 1–2).

Remote commands are space-joined already-validated tokens.  This module does
not POSIX-quote, escape, or launch OpenSSH.

A serve session token is generated by the desktop host for one start attempt,
passed as an argv token, and persisted only as a hash in remote owner metadata.
"""

from __future__ import annotations

import hashlib
import re
import secrets
from typing import Iterable, Sequence


REMOTE_PYTHON_REQUIRED = "REMOTE_PYTHON_REQUIRED"
R5_OWNERSHIP_NOT_IMPLEMENTED = "R5_OWNERSHIP_NOT_IMPLEMENTED"
REMOTE_SESSION_TOKEN_INVALID = "REMOTE_SESSION_TOKEN_INVALID"
REMOTE_ENTRY_RELATIVE = "desktop/python-webview-shell/remote_entry.py"
LOOPBACK_HOST = "127.0.0.1"
MAX_PROBE_BYTES = 4096
SESSION_TOKEN_HEX_BYTES = 16

POSIX_PATH_PATTERN = re.compile(r"^/[A-Za-z0-9._/-]+$")
SAFE_TOKEN_PATTERN = re.compile(r"^[A-Za-z0-9._/=:-]+$")

FORBIDDEN_FRAGMENTS = (
    "&&",
    "||",
    ";",
    "2>&1",
    ">/dev/null",
    "$(",
    "`",
    "bash -lc",
    "python -c",
    "python3 -c",
    "cd --",
    "<<",
)

BARE_INTERPRETERS = frozenset({"python", "python3"})


class RemoteCommandError(RuntimeError):
    def __init__(self, code: str, detail: str = "") -> None:
        self.code = code
        message = code if not detail else f"{code}: {detail}"
        super().__init__(message)


def validated_posix_path(value: object, field: str) -> str:
    if not isinstance(value, str):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", f"{field} must be a string")
    if any(ord(character) < 32 or character == "\x7f" for character in value):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", f"{field} contains a control character")
    if value == "/":
        raise RemoteCommandError(
            "REMOTE_PROTOCOL_INVALID",
            f"{field} must not be the Linux filesystem root",
        )
    if not POSIX_PATH_PATTERN.fullmatch(value):
        raise RemoteCommandError(
            "REMOTE_PROTOCOL_INVALID",
            f"{field} must match ^/[A-Za-z0-9._/-]+$",
        )
    if value.endswith("/"):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", f"{field} must not have a trailing slash")
    segments = value.split("/")[1:]
    if not segments or any(segment in {"", ".", ".."} for segment in segments):
        raise RemoteCommandError(
            "REMOTE_PROTOCOL_INVALID",
            f"{field} must not contain empty, '.' or '..' segments",
        )
    return value


def require_safe_token(token: str) -> str:
    if token in BARE_INTERPRETERS:
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "bare python interpreter is not a token")
    if token == "-c":
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "python -c is not a token")
    if not SAFE_TOKEN_PATTERN.fullmatch(token):
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", f"unsafe token {token!r}")
    return token


def require_session_token(value: object) -> str:
    """Require a caller-supplied runtime token. Do not invent a persisted default."""

    if value is None or value == "":
        raise RemoteCommandError(
            R5_OWNERSHIP_NOT_IMPLEMENTED,
            "session_token must be supplied by the desktop start attempt",
        )
    if not isinstance(value, str):
        raise RemoteCommandError(REMOTE_SESSION_TOKEN_INVALID, "session_token must be a string")
    if set(value) <= {"0"}:
        raise RemoteCommandError(
            REMOTE_SESSION_TOKEN_INVALID,
            "all-zero sentinel is not a runtime ownership token",
        )
    return require_safe_token(value)


def generate_session_token() -> str:
    """Return a cryptographically random token that satisfies the argv grammar."""

    while True:
        token = secrets.token_hex(SESSION_TOKEN_HEX_BYTES)
        if set(token) <= {"0"}:
            continue
        return require_session_token(token)


def token_hash(value: object) -> str:
    token = require_session_token(value)
    return hashlib.sha256(token.encode("ascii")).hexdigest()


def path_identity(value: str) -> str:
    canonical = validated_posix_path(value, "path")
    return hashlib.sha256(canonical.encode("ascii")).hexdigest()


def forbidden_fragments(command: str) -> tuple[str, ...]:
    return tuple(fragment for fragment in FORBIDDEN_FRAGMENTS if fragment in command)


def join_remote_tokens(tokens: Sequence[str]) -> str:
    validated = [require_safe_token(token) for token in tokens]
    if not validated:
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "remote command has no tokens")
    command = " ".join(validated)
    hits = forbidden_fragments(command)
    if hits:
        raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "forbidden fragments: " + ",".join(hits))
    return command


def remote_entry_path(app_dir: str) -> str:
    root = validated_posix_path(app_dir, "remote_app_dir")
    return validated_posix_path(f"{root}/{REMOTE_ENTRY_RELATIVE}", "remote_entry")


def require_remote_python(value: object) -> str:
    if value is None or value == "":
        raise RemoteCommandError(REMOTE_PYTHON_REQUIRED)
    return validated_posix_path(value, "remote_python")


def probe_tokens(*, remote_python: object, remote_app_dir: str, remote_data_dir: str) -> list[str]:
    python = require_remote_python(remote_python)
    app = validated_posix_path(remote_app_dir, "remote_app_dir")
    data = validated_posix_path(remote_data_dir, "remote_data_dir")
    return [
        python,
        "-I",
        "-B",
        remote_entry_path(app),
        "probe",
        "--app-dir",
        app,
        "--data-dir",
        data,
    ]


def serve_tokens(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    remote_port: int,
    local_forward_port: int,
    session_token: object,
    host: str = LOOPBACK_HOST,
) -> list[str]:
    python = require_remote_python(remote_python)
    app = validated_posix_path(remote_app_dir, "remote_app_dir")
    data = validated_posix_path(remote_data_dir, "remote_data_dir")
    token = require_session_token(session_token)
    return [
        python,
        "-I",
        "-B",
        remote_entry_path(app),
        "serve",
        "--app-dir",
        app,
        "--data-dir",
        data,
        "--host",
        require_safe_token(host),
        "--port",
        require_safe_token(str(remote_port)),
        "--public-port",
        require_safe_token(str(local_forward_port)),
        "--session-token",
        token,
        "--exit-with-parent",
    ]


def stop_owned_tokens(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    session_token: object,
) -> list[str]:
    python = require_remote_python(remote_python)
    app = validated_posix_path(remote_app_dir, "remote_app_dir")
    data = validated_posix_path(remote_data_dir, "remote_data_dir")
    token = require_session_token(session_token)
    return [
        python,
        "-I",
        "-B",
        remote_entry_path(app),
        "stop-owned",
        "--data-dir",
        data,
        "--session-token",
        token,
    ]


def join_probe_command(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
) -> str:
    tokens = probe_tokens(
        remote_python=remote_python,
        remote_app_dir=remote_app_dir,
        remote_data_dir=remote_data_dir,
    )
    scan_tokens_for_live_ssh(tokens)
    return join_remote_tokens(tokens)


def join_serve_command(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    remote_port: int,
    local_forward_port: int,
    session_token: object,
    host: str = LOOPBACK_HOST,
) -> str:
    tokens = serve_tokens(
        remote_python=remote_python,
        remote_app_dir=remote_app_dir,
        remote_data_dir=remote_data_dir,
        remote_port=remote_port,
        local_forward_port=local_forward_port,
        session_token=session_token,
        host=host,
    )
    scan_tokens_for_live_ssh(tokens)
    return join_remote_tokens(tokens)


def join_stop_owned_command(
    *,
    remote_python: object,
    remote_app_dir: str,
    remote_data_dir: str,
    session_token: object,
) -> str:
    tokens = stop_owned_tokens(
        remote_python=remote_python,
        remote_app_dir=remote_app_dir,
        remote_data_dir=remote_data_dir,
        session_token=session_token,
    )
    scan_tokens_for_live_ssh(tokens)
    return join_remote_tokens(tokens)


def scan_tokens_for_live_ssh(argv: Iterable[str]) -> None:
    """Refuse accidentally embedding a live ssh invocation in remote tokens."""

    for token in argv:
        if token == "ssh" or token.endswith("/ssh") or token.endswith("ssh.exe"):
            raise RemoteCommandError("REMOTE_PROTOCOL_INVALID", "live ssh is not a remote token")
