"""Format primitives for normalized Work Stack storage."""

from .canonical import (
    CANONICAL_JSON_FORMAT,
    MAX_CANONICAL_INTEGER,
    CanonicalJsonError,
    canonical_json_bytes,
    canonical_sha256,
)
from .contracts import (
    ContractViolation,
    StorageContractError,
    load_schema_catalog,
    require_valid_by_format,
    validate_by_format,
    validate_instance,
)
from .validation import (
    StoragePathValidationReport,
    StorageValidationIssue,
    validate_storage_path,
)
from .layout import (
    RECORD_KINDS,
    STREAM_KINDS,
    RecordLocation,
    StorageLayoutError,
    StreamLocation,
    V4Layout,
)
from .reader import (
    ReadArtifact,
    StorageReadError,
    V4ReadLimits,
    V4ReadResult,
    read_v4,
)
from .manifest import (
    MANIFEST_FORMAT,
    MANIFEST_VERSION,
    V4Manifest,
    V4ManifestError,
    build_v4_manifest,
    construct_v4_manifest,
)
from .repository import (
    RepositoryAdmission,
    RepositoryAdmissionError,
    V4ReadOnlyRepository,
    V4ReadOnlyStoreAdapter,
    admit_released_repository,
    admit_test_read_repository,
)
from .document_repository import (
    DocumentRepository,
    StoreDocumentRepository,
    WorkspaceDocument,
)
from .semantic import (
    SemanticProjectionError,
    V4SemanticSource,
    WorkspaceSnapshot,
    semantic_source_from_v4_read,
    snapshot_from_v3_documents,
    snapshot_from_v4,
)
from .migration_conversion import (
    V3ConversionError,
    V4Conversion,
    convert_v3_documents,
)
from .migration_paths import MigrationPathError, MigrationPaths, plan_migration_paths
from .migration_source import (
    FrozenV3Source,
    V3BackupArtifact,
    V3BackupVerification,
    V3MigrationSourceError,
    V3SourceArtifact,
    V3SourceLimits,
    create_verified_v3_backup,
    freeze_v3_source,
    verify_v3_backup,
    verify_v3_source_unchanged,
)
from .migration import (
    MIGRATION_ALGORITHM_VERSION,
    MigrationExecution,
    MigrationPlan,
    MigrationPreview,
    StorageMigrationError,
    execute_v3_migration,
    load_migration_receipt,
    plan_v3_migration,
    preview_v3_migration,
    resume_v3_migration,
    verify_v3_migration,
    verify_v3_migration_artifacts,
)

__all__ = [
    "CANONICAL_JSON_FORMAT",
    "MAX_CANONICAL_INTEGER",
    "CanonicalJsonError",
    "canonical_json_bytes",
    "canonical_sha256",
    "ContractViolation",
    "StorageContractError",
    "load_schema_catalog",
    "require_valid_by_format",
    "validate_by_format",
    "validate_instance",
    "StoragePathValidationReport",
    "StorageValidationIssue",
    "validate_storage_path",
    "RECORD_KINDS",
    "STREAM_KINDS",
    "RecordLocation",
    "StorageLayoutError",
    "StreamLocation",
    "V4Layout",
    "ReadArtifact",
    "StorageReadError",
    "V4ReadLimits",
    "V4ReadResult",
    "read_v4",
    "MANIFEST_FORMAT",
    "MANIFEST_VERSION",
    "V4Manifest",
    "V4ManifestError",
    "build_v4_manifest",
    "construct_v4_manifest",
    "RepositoryAdmission",
    "RepositoryAdmissionError",
    "V4ReadOnlyRepository",
    "V4ReadOnlyStoreAdapter",
    "admit_released_repository",
    "admit_test_read_repository",
    "DocumentRepository",
    "StoreDocumentRepository",
    "WorkspaceDocument",
    "SemanticProjectionError",
    "V4SemanticSource",
    "WorkspaceSnapshot",
    "semantic_source_from_v4_read",
    "snapshot_from_v3_documents",
    "snapshot_from_v4",
    "V3ConversionError",
    "V4Conversion",
    "convert_v3_documents",
    "MigrationPathError",
    "MigrationPaths",
    "plan_migration_paths",
    "FrozenV3Source",
    "V3BackupArtifact",
    "V3BackupVerification",
    "V3MigrationSourceError",
    "V3SourceArtifact",
    "V3SourceLimits",
    "create_verified_v3_backup",
    "freeze_v3_source",
    "verify_v3_backup",
    "verify_v3_source_unchanged",
    "MIGRATION_ALGORITHM_VERSION",
    "MigrationExecution",
    "MigrationPlan",
    "MigrationPreview",
    "StorageMigrationError",
    "execute_v3_migration",
    "load_migration_receipt",
    "plan_v3_migration",
    "preview_v3_migration",
    "resume_v3_migration",
    "verify_v3_migration",
    "verify_v3_migration_artifacts",
]
